on:
  pull_request:
    branches:
#       - 'master'
      - develop/*
      - release/*
    types: [closed]
    paths: src/main/resources/db/mig.sql

jobs:
  changedfile:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      migfile: ${{ steps.changes.outputs.migfile }}
      datetime: ${{ steps.datetime.outputs.datetime }}
      pull_request_user: ${{ steps.pull_request.outputs.result }}
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 'Get Changed File'
      id: changes
      shell: bash
      run: |
        mydiff=$(git diff HEAD^..HEAD --diff-filter=AM src/main/resources/db/mig.sql | sed -n '3,$p' | egrep "^\+|^\-")
        mydiff="${mydiff//'%'/'%25'}"
        mydiff="${mydiff//$'\n'/'%0A'}"
        mydiff="${mydiff//$'\r'/'%0D'}"
        echo "::set-output name=migfile::$mydiff"
    
    - name: 'Get JST Datetime'
      id: datetime
      run: echo "::set-output name=datetime::$(date +'%Y-%m-%d %H:%M:%S')"
      env:
        TZ: 'Asia/Tokyo'

    - name: 'Get Pull-Request Opener'
      uses: actions/github-script@v4
      id: pull_request_user
      with:
        script: return context.payload.pull_request.user.login
        result-encoding: string

  slackNotification:
    runs-on: ubuntu-latest
    needs: changedfile
    if: ${{needs.changedfile.outputs.migfile}}
    steps:
      - name: 'Send Slack Notification'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: github-actions-test
          SLACK_TITLE: 'マイグレーションのお知らせ :bell:'
          SLACK_USERNAME: ${{ needs.changedfile.outputs.pull_request_user }}
          SLACK_MESSAGE: |
            PR者: ${{ needs.changedfile.outputs.pull_request_user }}
            日時: ${{ needs.changedfile.outputs.datetime }}
            変更差分: 
            ${{ needs.changedfile.outputs.migfile }}
