on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  notification:
  if: github.event.pull_request.merged == true
  runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Checkout

        - name: Slack Notification on Success
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_CHANNEL: github-actions-test
            SLACK_COLOR: 'green'
            SLACK_MESSAGE: 'Post Content :rocket:'
            SLACK_TITLE: Post Title
            SLACK_USERNAME: masshun
  
# on:
#   pull_request
  
# jobs:
#   comment:
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#             git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com/masshun/design-pattern
#             rm everything but the .git directory
#             copy src/adapter/extendpattern
#             cd src/main/kotlin/com/example/demo
#             git add .
#             git diff-index --quiet HEAD || git commit -m "Automatic publish from github.com/project"
#             git push target master
