on:
  pull_request:
    branches:
      - 'master'
    types: [closed]
    paths: src/main/resources/db/mig.sql

jobs:
  changedfile:
    runs-on: ubuntu-latest
    outputs:
      migfile: ${{ steps.changes.outputs.file }}
    steps:
    - name: 'Checkout'
      if: github.event.pull_request.merged == true
      uses: actions/checkout@v2
#       with:
#         fetch-depth: 2

#     - name: 'Fetch'
#       run: git fetch --depth 1 origin master

    - name: 'Get changed file'
      id: changes
      run: |
        echo "::set-output name=migfile::$(git diff HEAD --diff-filter=M ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .sql$ | xargs)"
        echo "hogehogehoge"

  slackNotification:
    runs-on: ubuntu-latest
    needs: changedfile
    if: ${{needs.changedfile.outputs.migfile}}
    steps:
      - name: 'Slack Notification'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: github-actions-test
          SLACK_MESSAGE: hogehoge
          SLACK_TITLE: マイグレーションのお知らせ
          SLACK_USERNAME: masshun
