on:
  pull_request:
    branches:
      - 'master'
    types: [closed]
    paths: src/main/resources/db/mig.sql

jobs:
  changedfile:
    runs-on: ubuntu-latest
    outputs:
      migfile: ${{ steps.changes.outputs.file }}
    steps:
    - name: 'Checkout'
      uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: 'Get changed file'
      if: github.event.pull_request.merged == true
      id: changes
      run: |
        echo "::set-output name=migfile::$(git diff --diff-filter=M src/main/resources/db/mig.sql)"

  slackNotification:
    runs-on: ubuntu-latest
    needs: changedfile
    if: ${{needs.changedfile.outputs.migfile}}
    steps:
      - name: 'Slack Notification'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: github-actions-test
          SLACK_MESSAGE: hogehoge
          SLACK_TITLE: マイグレーションのお知らせ
          SLACK_USERNAME: masshun
