on:
  pull_request:
    branches:
      - 'master'
    types: [closed]
    paths: src/main/resources/db/mig.sql

jobs:
  changedfile:
    runs-on: ubuntu-latest
    outputs:
      migfile: ${{ steps.changes.outputs.migfile }}
      datetime: ${{ steps.datetime.outputs.datetime }}
      milestone: ${{ steps.milestone.outputs.result }}
    steps:
    - name: 'Checkout'
      uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: 'Get changed file'
      if: github.event.pull_request.merged == true
      id: changes
      shell: bash
      run: |
        mydiff=$(git diff HEAD^..HEAD --diff-filter=AM src/main/resources/db/mig.sql)
        mydiff="${mydiff//'%'/'%25'}"
        mydiff="${mydiff//$'\n'/'%0A'}"
        mydiff="${mydiff//$'\r'/'%0D'}"
        echo "::set-output name=migfile::$mydiff"
    
    - name: 'Get JST datetime'
      id: datetime
      run: echo "::set-output name=datetime::$(date +'%Y-%m-%d %H:%M:%S')"
      env:
        TZ: 'Asia/Tokyo'
    
    - name: 'Get pullRequest milestone'
      uses: actions/github-script@v4
      id: milestone
      with:
        script: return context.payload.pull_request.milestone.title
        result-encoding: string

  slackNotification:
    runs-on: ubuntu-latest
    needs: changedfile
    if: ${{needs.changedfile.outputs.migfile}}
    steps:
      - name: 'Slack Notification'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: github-actions-test
          SLACK_MESSAGE: ${{needs.changedfile.outputs.migfile}} '%0A' ${{needs.changedfile.outputs.datetime}} '%0A' ${{ needs.changedfile.outputs.milestone }}
          SLACK_TITLE: マイグレーションのお知らせ
