on:
  pull_request:
    branches:
      - 'master'
    types: [closed]
    paths: src/main/resources/db/mig.sql

jobs:
  changedFile:
    runs-on: ubuntu-latest
    outputs:
      file: ${{ steps.changes.outputs.file }}
    steps:
    - name: 'Checkout'
      if: github.event.pull_request.merged == true
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

#     - name: 'Fetch'
#       run: git fetch --depth 1 origin master

    - name: 'Get changed file'
      run: |
        echo "::set-output name=file::$(git diff HEAD --diff-filter=M src/main/resources/db/mig.sql)"
        echo "hogehogehoge"

  slackNotification:
    runs-on: ubuntu-latest
    needs: changedFile
    if: ${{needs.changedFile.outputs.file}}
    steps:
      - name: 'Slack Notification'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: github-actions-test
          SLACK_MESSAGE: echo ${{needs.changedFile.outputs.file}}
          SLACK_TITLE: マイグレーションのお知らせ
          SLACK_USERNAME: masshun
