on:
  pull_request:
    branches:
      - 'master'
    types: [closed]
    paths: src/main/resources/db/mig.sql

jobs:
  changedfile:
    runs-on: ubuntu-latest
    outputs:
      migfile: ${{ steps.changes.outputs.migfile }}
    steps:
    - name: 'Checkout'
      uses: actions/checkout@master
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: 'Get changed file'
      if: github.event.pull_request.merged == true
      id: changes
      shell: bash
      run: |
        git fetch
        git diff origin/${{github.base_ref}}..${{github.head_ref}} --diff-filter=AM > mydiff
        cat mydiff
        echo "::set-output name=migfile::$(cat mydiff)"

  slackNotification:
    runs-on: ubuntu-latest
    needs: changedfile
    if: ${{needs.changedfile.outputs.migfile}}
    steps:
      - name: 'Slack Notification'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: github-actions-test
          SLACK_MESSAGE: ${{needs.changedfile.outputs.migfile}}
          SLACK_TITLE: マイグレーションのお知らせ
          SLACK_USERNAME: masshun
